### ISSUE TITLE
No deployment instructions

### ISSUE THREAD

**Issue by lxdv** [PMICources/InitialProject#6]
Can't find any instruction how to run it

**Comment by PMICources** [comment]
@Ixdv
[Инструкция по использованию CMake для имбицилов](https://tuannguyen68.gitbooks.io/learning-cmake-a-beginner-s-guide/content/chap1/chap1.html)
[Еще одна](http://derekmolloy.ie/hello-world-introductions-to-cmake/)

И вообще, CMake сам по себе инструкция.
